// 平台配置常量
export const PLATFORMS_CONFIG = {
  version: "1.0.0",
  updatedAt: new Date().toISOString(),
  settings: {
    platforms: [
      {
        id: 1,
        key: "zhihu",
        name: "知乎",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=zhihu&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=zhihu&latest",
        method: "GET" as const,
        enabled: true,
        priority: 1,
      },
      {
        id: 2,
        key: "weibo",
        name: "微博",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=weibo&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=weibo&latest",
        method: "GET" as const,
        enabled: true,
        priority: 2,
      },
      {
        id: 3,
        key: "coolapk",
        name: "酷安",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=coolapk&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=coolapk&latest",
        method: "GET" as const,
        enabled: true,
        priority: 3,
      },
      {
        id: 4,
        key: "wallstreet",
        name: "华尔街见闻",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=wallstreetcn-hot&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=wallstreetcn-hot&latest",
        method: "GET" as const,
        enabled: true,
        priority: 4,
      },
      {
        id: 5,
        key: "douyin",
        name: "抖音",
        apiUrl: "https://www.douyin.com/aweme/v1/hot/search/list/?device_platform=webapp&aid=6383&channel=channel_pc_web&detail_list=1",
        latestApiUrl: "https://www.douyin.com/aweme/v1/hot/search/list/?device_platform=webapp&aid=6383&channel=channel_pc_web&detail_list=1",
        method: "GET" as const,
        enabled: true,
        priority: 5,
      },
      {
        id: 6,
        key: "hupu",
        name: "虎扑",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=hupu&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=hupu&latest",
        method: "GET" as const,
        enabled: true,
        priority: 6,
      },
      {
        id: 7,
        key: "tieba",
        name: "百度贴吧",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=tieba&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=tieba&latest",
        method: "GET" as const,
        enabled: true,
        priority: 7,
      },
      {
        id: 8,
        key: "toutiao",
        name: "今日头条",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=toutiao&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=toutiao&latest",
        method: "GET" as const,
        enabled: true,
        priority: 8,
      },
      {
        id: 9,
        key: "thepaper",
        name: "澎湃新闻",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=thepaper&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=thepaper&latest",
        method: "GET" as const,
        enabled: true,
        priority: 9,
      },
      {
        id: 10,
        key: "cailianpress",
        name: "财联社",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=cls-hot&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=cls-hot&latest",
        method: "GET" as const,
        enabled: true,
        priority: 10,
      },
      {
        id: 11,
        key: "xueqiu",
        name: "雪球",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=xueqiu-hotstock&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=xueqiu-hotstock&latest",
        method: "GET" as const,
        enabled: true,
        priority: 11,
      },
      {
        id: 12,
        key: "bilibili-hot",
        name: "B站热搜",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=bilibili-hot-search&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=bilibili-hot-search&latest",
        method: "GET" as const,
        enabled: true,
        priority: 12,
      },
      {
        id: 13,
        key: "bilibili-popular",
        name: "B站热门视频",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=bilibili-hot-video&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=bilibili-hot-video&latest",
        method: "GET" as const,
        enabled: true,
        priority: 13,
      },
      {
        id: 14,
        key: "bilibili-ranking",
        name: "B站排行榜",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=bilibili-ranking&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=bilibili-ranking&latest",
        method: "GET" as const,
        enabled: true,
        priority: 14,
      },
      {
        id: 15,
        key: "baidu",
        name: "百度热搜",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=baidu&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=baidu&latest",
        method: "GET" as const,
        enabled: true,
        priority: 15,
      },
      {
        id: 16,
        key: "nowcoder",
        name: "牛客",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=nowcoder&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=nowcoder&latest",
        method: "GET" as const,
        enabled: true,
        priority: 16,
      },
      {
        id: 17,
        key: "sspai",
        name: "少数派",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=sspai&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=sspai&latest",
        method: "GET" as const,
        enabled: true,
        priority: 17,
      },
      {
        id: 18,
        key: "juejin",
        name: "稀土掘金",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=juejin&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=juejin&latest",
        method: "GET" as const,
        enabled: true,
        priority: 18,
      },
      {
        id: 19,
        key: "ifeng",
        name: "凤凰网",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=ifeng&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=ifeng&latest",
        method: "GET" as const,
        enabled: true,
        priority: 19,
      },
      {
        id: 20,
        key: "chongbuluo",
        name: "虫部落",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=chongbuluo-hot&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=chongbuluo-hot&latest",
        method: "GET" as const,
        enabled: true,
        priority: 20,
      },
      {
        id: 21,
        key: "douban",
        name: "豆瓣",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=douban&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=douban&latest",
        method: "GET" as const,
        enabled: true,
        priority: 21,
      },
      {
        id: 22,
        key: "steam",
        name: "Steam",
        apiUrl: "https://news.quanyouhulian.com/api/s?id=steam&latest",
        latestApiUrl: "https://news.quanyouhulian.com/api/s?id=steam&latest",
        method: "GET" as const,
        enabled: true,
        priority: 22,
      },
    ],
    tags: {
      visible: [
        "zhihu",
        "weibo",
        "coolapk",
        "wallstreet",
        "douyin",
        "hupu",
        "tieba",
        "toutiao",
        "thepaper",
        "cailianpress",
        "xueqiu",
        "bilibili-hot",
        "bilibili-popular",
        "bilibili-ranking",
        "baidu",
        "nowcoder",
        "sspai",
        "juejin",
        "ifeng",
        "chongbuluo",
        "douban",
        "steam",
      ],
      hidden: [],
    },
  },
} as const;

export type PlatformConfig = typeof PLATFORMS_CONFIG.settings.platforms[number];
export type TagsConfig = typeof PLATFORMS_CONFIG.settings.tags;
